### ISSUE TITLE
Improvements to editing

### ISSUE THREAD

**Issue by pressRtowin** [Valent-in/retropad-editor#1]
Just some ideas to make editing easier:

- the ability to move and scale multiple buttons at once (so you can move/scale the d pad for instance without having to manually reposition every button individually)
- temporarily saving groups of buttons so they can be quickly re-added to other layers/layouts
- translate coordinates to a more user-friendly system (i.e. use a grid with (0,0) at the center of the screen, but the output file would still be in the correct format for retroarch). Aligning a d pad and abxy at (-.3864,-.2764) and (.3864,-.2864) respectively makes far more intuitive sense (and requires less mental math) than (.1136,.7764) and (.8864,.7764).

**Comment by Valent-in** [comment]
> * the ability to move and scale multiple buttons at once

Was in my initial TODO. But this was abandoned because of ~~lazyness~~ conflicts between drag-to-select and drag-to-scroll on touchscreen. Maybe I'll try to do something with long tap to initiate selection. 

> * temporarily saving groups of buttons

I had similar idea. But it has no sense without group selection. So "Duplicate current overlay" option was created for this purpose.

> * translate coordinates to a more user-friendly system (i.e. use a grid with (0,0) at the center of the screen

No, I don't want to do that. Y-axis should be centered too in this case. And also flipped - positive values upwards is convenient approach. Now it just shows values from config and such changes may confuse users who are familiar with manual config editing.

**Comment by Valent-in** [comment]
Hmm... I think flip button near X-axis slider is much easier solution than double recalculations

**Comment by Valent-in** [comment]
> Oh yeah that could work. Just a button to mirror the button

This is simple thing. Already implemented.

> A "rotate 90°" button could also be very helpful for rotating buttons in various aspect ratios

You don't need to recalculate those numbers actually - "Quad" already does this. Yes, for non-square shapes too: note dimensions for button, click W-Quad, note new size, restore previous width, click H-Quad, note new size, restore previous height... now you have width and height for 90deg. rotated button. This action looks a bit cumbersome, but you need to copy values in any case to create up-down left-right pairs with same size.

**Comment by Valent-in** [comment]
Group selection is working now (two-finger tap on touchscreen).

**Comment by Valent-in** [comment]
Copy-pasting buttons may cause invisible duplicates (same size and position). And it is already possible to copy whole overlay.

**Comment by Valent-in** [comment]
I don't want to clutter left bar with new functions as it uses same (flexbox) layout for desktop and mobile. Maybe single small button to show "selection" menu with copy-paste, lower-raise, and other functions. But lower-raise is quite specific option. And I don't think copying same button will help editing much (still need to edit position, command, and image).

Maybe I'll implement selection menu later. But not in close time.
