### ISSUE TITLE
Not deleting image files when export

### ISSUE THREAD

**Issue by kazile** [Valent-in/retropad-editor#2]
Hi, first, I want to say thanks for the online app; it's very useful and helps me understand cfg files.

The problem I'm encountering is that when I export the images, it includes all the images that I deleted using the "Delete button" in both overlays, as well as those deleted by the "Delete overlay" button. I'm creating a custom Gameboy overlay and have removed L1, L2, R1, R2, etc., as well as analog overlays, but when I export the images, all these deleted images and more are downloaded.

Sorry for my bad English; I speak Spanish.

Greetings

**Comment by Valent-in** [comment]
Hi.
Images are packed in static zip file. It contains full image set from 'flat' overlays. So this is just download link, unlike config export.

I don't see any reasons to remove unused images as they has less than 0.5 MB in total. Also there is no need to redownload and unpack for next overlays. Just put .cfg files in same folder.
